{% set name = "gradio" %}
{% set version = "gradio@5.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gradio-app/gradio/archive/{{ version }}.tar.gz
  sha256: b49b35c770e34d95e04d394e95ba8413d76c6706e13557e3b18be1720326a86d

build:
  entry_points:
    - gradio = gradio.cli:cli
    - upload_theme = gradio.themes.upload_theme:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - gradio
  commands:
    - pip check
    - gradio --help
    - upload_theme --help
  requires:
    - pip

about:
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sclare87
